version: 2.1
orbs: 
  codecov: codecov/codecov@3.1.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install g++ cmake valgrind
      - run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS_DEBUG="-g -fsanitize=address -std=c++17" . && make -j8
      - run: ctest -V
workflows:
  upload-to-codecov:
    jobs:
      - build
      - codecov/upload