version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install g++ cmake valgrind pybind11
      - run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS_DEBUG="-g -fsanitize=address -std=c++17" . && make -j8
      - run: ctest -V
